### ISSUE TITLE
Feature: Search functionality for contacts

### ISSUE THREAD

**Issue by commitshappen** [st-charles/DSCP-Partner-Portal-API#5]
As an authenticated user I want to search contacts so that I can see a contact's matching first name and matching last name and matching email and matching phone number and matching address.

**Comment by freeranger** [comment]
Hi,

Given this is an API project, the requirements could be specified in more detail to ensure you get what you want, especially when an API is fairly precise in terms of what it accepts, what status codes it returns etc.   With the definition you have given so far, there are any number of implementations which satisfy the requirement but which may not satisfy what you actually want to achieve.

* Should this be a POST or a GET for example?   A GET might seem the "obvious" answer, and indeed logicaly what you are doing is a GET.  In theory, it is easier to test also - though you have to be authenticated, so you can't just navigate to the api end point in a browser to do a request (or should unauthenticated people be able to do searches?).  
A GET with a single search term is pretty concise - posting JSON for a single field may seem excessive - but if your search terms are going to get more complex then a POST _may_ make more sense:
```
{
    "first_name": ["foo", "bar"],
    "last_name": "baz"
}
```
this could be a search for any one of these first names + this last name, or you could go full blown odata and implement that standard.
You can send a GET with a body but routers etc may strip that off so it's not really a reliable thing to do - hence POST is sometimes use where you are logically doing a GET.

* What can you search on - any field or just a few?  That may inform your GET/POST choice.

* Where is the endpoint - `/contacts?last_name=Jones` or a specialisation: `/contacts/$filter?last_name=Jones`

* What happens when there are no matches - a 404 or a 200 and an empty array of matches?  A 200 probably makes more sense since the request didn't fail - it just didn't have any matches.

* Also, consider writing the features directly in here (or even linking to a feature file you have created in the repo, tagging it as @wip - if memory serves, will mean they do not fail the build just because the steps aren't implemented, so it will carry on being green until these are done.

The feature file for this might look something like:
```
Feature: Search Contacts
  In order to the contacts I want
  I need to be able to search for them.

  Background:
    Given the system knows about the following user:
      | first_name       | last_name      | email                       | password  |
      | Charles          | Xavier         | x@westchester.ny            | jeanrules |

    And the system knows about the following contacts:
      | first_name       | last_name      | email                     |
      | Reed             | Richards       | mrfantastic@ff.com        |
      | Jessica          | Jones          | jewel@brooklyn.ny         |
      | Rick             | Jones          | abomb@smash.org           |


  Scenario: Search contacts (unauthenticated client)
    When the client sends a GET request to /contacts/$filter?last_name=Jones 
    (or alternatively is it simply /contacts?last_name=Jones ??)
    Then a 401 status code is returned


  Scenario: Search contacts (authenticated client) (using the other end point for illustration)
    Given the client authenticates as x@westchester.ny
    When the client sends a GET request to  /contacts?last_name=Jones
    Then a 200 status code is returned
    And the response should be JSON
    And the JSON should contain:
      """
        [
          { "first_name": "Jessica", "last_name": "Jones", "email": "jewel@brooklyn.ny" },
          { "first_name": "Rick", "last_name": "Jones", "email": "abomb@smash.org" }
        ]
      """


  Scenario: Search contacts (using POST instead)
    Given the client authenticates as x@westchester.ny
    When the client sends a POST request to /contacts/$filter:
      """
          { "last_name": "Jones" }
      """
    Then a 200 status code is returned
    And the response should be JSON
    And the JSON should contain:
      """
        [
          { "first_name": "Jessica", "last_name": "Jones", "email": "jewel@brooklyn.ny" },
          { "first_name": "Rick", "last_name": "Jones", "email": "abomb@smash.org" }
        ]
      """


  Scenario: Search contacts resulting in no match
    Given the client authenticates as x@westchester.ny
    When the client sends a GET request to  /contacts/$filter?email=mxyzptlk@5th.dimension
    Then a 200 status code is returned
    And the response should be JSON
    And the JSON should be an empty array:
      """
        [
        ]
      """


  Scenario: Search contacts resulting in no match (404 instead)
    Given the client authenticates as x@westchester.ny
    When the client sends a GET request to  /contacts/$filter?email=mxyzptlk@5th.dimension
    Then a 404 status code is returned
```
Obviously this would be fleshed out with a few more examples, e.g. searching on multiple critera eta...

**Comment by commitshappen** [comment]
Hey @freeranger,

Good feedback. The way that I envision it is a user visits the /contacts path and sees all available contacts. S/he can then type in *any* string of characters into a search box, which then filters out the contacts to match that string in any capacity. 

As for the endpoint, I therefore feel it could be as simple as `/contacts?filter=Parker`, which would then do a deep search and return any contact whose attributes match. Where the challenge comes is where I want a user to be able to type "Peter Parker" into the search box and for that search to return a contact whose attributes match both "Peter" and "Parker". (I'm not sure how to go about tacking the latter).

I also believe a request that doesn't have any data to return should be treated as a 204 (the server successfully processed the request, but is not returning any content) instead of a 404.

When it comes to a POST instead of a GET request, I'm initially inclined to say GET. I imagine the client-side app will securely store the JWT in a session/cookie upon login, which will then be sent in each request header. If you think there's a better way, I'd be open to it.

Thus a feature file would look something along the lines of the following, knowing that a test for a "Peter Parker" search still needs to be added: 
```
Feature: Search Contacts
  In order to the contacts I want
  I need to be able to search for them.

  Background:
    Given the system knows about the following user:
      | first_name       | last_name      | email                       | password  |
      | Charles          | Xavier         | x@westchester.ny            | jeanrules |

    And the system knows about the following contacts:
      | first_name       | last_name      | email                     |
      | Reed             | Richards       | mrfantastic@ff.com        |
      | Jessica          | Jones          | jewel@brooklyn.ny         |
      | Rick             | Jones          | abomb@smash.org           |


  Scenario: Search contacts (unauthenticated client)
    When the client sends a GET request to /contacts?filter=Jones
    Then a 401 status code is returned


  Scenario: Search contacts (authenticated client)
    Given the client authenticates as x@westchester.ny
    When the client sends a GET request to  /contacts?filter=Jones
    Then a 200 status code is returned
    And the response should be JSON
    And the JSON should contain:
      """
        [
          { "first_name": "Jessica", "last_name": "Jones", "email": "jewel@brooklyn.ny" },
          { "first_name": "Rick", "last_name": "Jones", "email": "abomb@smash.org" }
        ]
      """


  Scenario: Search contacts mixed case (authenticated client)
    Given the client authenticates as x@westchester.ny
    When the client sends a GET request to  /contacts?filter=JoNEs
    Then a 200 status code is returned
    And the response should be JSON
    And the JSON should contain:
      """
        [
          { "first_name": "Jessica", "last_name": "Jones", "email": "jewel@brooklyn.ny" },
          { "first_name": "Rick", "last_name": "Jones", "email": "abomb@smash.org" }
        ]
      """


  Scenario: Search contacts resulting in no match
    Given the client authenticates as x@westchester.ny
    When the client sends a GET request to  /contacts?filter=mxyzptlk@5th.dimension
    Then a 204 status code is returned
```

**Comment by freeranger** [comment]
Hey @commitshappen, 

> The way that I envision it is a user visits the /contacts path and sees all available contacts

I don't think you should look at it like that.  It may be hard to do, but divorce the API from the client application.  No user will be visiting the API, and the API end point address doesn't have to look anything like a UI address.  At this point we are only designing an API which will be used by other applications.

It sounds like you want full text search as opposed to filtering.  Filtering is a simple yes/no - partner=true is a simple test - you either are or you are not a partner.
`/contacts/$filter?partner=true` would be appropriate here.

Search is different - `/contacts/$search=peter` could match in multiple fields, multiple times.  How do you order the results (ranking)?   Is it a more important result if you match on first name rather than say, part of an address (10 Peters Avenue)?  More important if you match a whole word rather than part of a word (Peter vs Peters) etc?
When you search for Peter Parker, are you searching for the phrase "Peter Parker", or all contacts with "Peter" and "Parker" somewhere in any fields?  last name = Parker, address = 10 Peters Avenue?
Again, do you rank ones with both words in a single field higher than those in separate fields?  Those with the words adjacent  higher than those with the words spread out etc?

You might actually be better off with a document database such as elastic search or mongodb than a relational one like postgreSQL for this sort of thing - that's what they are good at, particularly elastic search.

> I also believe a request that doesn't have any data to return should be treated as a 204 (the server successfully processed the request, but is not returning any content) instead of a 404.

I definitely don't think it should be 404 but I threw it out there as it is an option.  204 is meant more for things like DELETE operations or other such ones where you simply wouldn't return any data.  If you look at the HTTP/1.1 spec: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

> The server has fulfilled the request but does not need to return an entity-body

It might be confusing to consumers of the API to receive this when they would normally expect a 200 with 0 or more results in the body.
It's your API so you can choose to return whatever you want (but document it - swagger or similar) but I think it would be more standard and expected to return a 200 in this case.

POST vs GET, again GET is probably more common - some would argue you are "submitting a search request" so POST is the way to go but I'm happy with GET until it becomes a problem.

Re:  token - you would need to do this regardless of the verb you use.
You could use local storage instead of cookies but cookies are probably more secure so I'd go with that.

**Comment by freeranger** [comment]
You might also want to allow search specifically only on certain fields - I am looking for someone names Peter - I don't care about Peter being part of the address, so you need to think about that - maybe that's /contacts/$filter?first_name=Peter type of thing?
Be careful though of adding too much to the API that you ultimately don't need!

**Comment by commitshappen** [comment]
> How do you order the results (ranking)? Is it a more important result if you match on first name rather than say, part of an address (10 Peters Avenue)? More important if you match a whole word rather than part of a word (Peter vs Peters) etc?

I would rank it like this, where the first item is most important: first_name, last_name, email, business_name, address, phone, phone_alt. All other attributes can be ignored in a search. I would also put more importance on a full match than partial. 

> When you search for Peter Parker, are you searching for the phrase "Peter Parker", or all contacts with "Peter" and "Parker" somewhere in any fields? last name = Parker, address = 10 Peters Avenue?
Again, do you rank ones with both words in a single field higher than those in separate fields? Those with the words adjacent higher than those with the words spread out etc?

I'd be looking for the full phrase, not pieces. The challenge, however, would be that first_name and last_name are separate and could be difficult to search in conjunction. Maybe the next question you had makes this a little easier.

> You might actually be better off with a document database such as elastic search or mongodb than a relational one like postgreSQL for this sort of thing - that's what they are good at, particularly elastic search.

I definitely see the value here. What about something like Redis for the db? I know it's supported by Heroku and can be easily implemented. I originally wanted to use Redis, but I just haven't done it before and didn't know how to start. 

> 204 is meant more for things like DELETE operations or other such ones where you simply wouldn't return any data. 

It would be best then to return a 200 status of an empty object. That would be easiest to implement for API users.

> POST vs GET, again GET is probably more common - some would argue you are "submitting a search request" so POST is the way to go but I'm happy with GET until it becomes a problem.

Let's stick with GET for now. What we'd be putting in the url can be exposed to the outside world, especially since we'll be implementing SSL. It will also make for easier AJAX requests.

**Comment by freeranger** [comment]
Hi,

Ranking is one of those things that is more complicated than it first seems, and that search engines do well (and databases with search support.  You say first_name is more important than last_name, but what if the last_name matches the search term ("Belle") whereas the first_name only contains it ("Anabelle") - which is more relevant then?  So then you have to think about scoring - a match on first_name anywhere scores 100, last_name scores 50, exact match +50, exact phrase (ie the whole word, not just the start of the word matching the search phrase) +20 or whatever...but then you need to ensure you don't "accidentally" rank the same as a more important match because your ranking boosts, +50, +20 etc are not at the right level...and the list goes on...so best not to try to implement your own ranking really if you can avoid it :}

Google search will, simplistically, find all matches containing any words and push those containing all words to the top - but you can still get to the ones matching only some of the words.
There are two problems with search: 1. not returning enough results, 2. returning too many results :)  If you always go with matching the full phrase then you rule out someone looking for Peter Parker  living on Ingram Street by searching "Parker Ingram" because all they know is it is someone with that surname on that street.
This is something that perhaps will need some experimentation once it's up and running to determine what makes most sense, giving the most relevant matches first.

Redis is not really designed with this use-case in mind AFAIK - it is an extremely fast in-memory key value store and is more geared towards fast retrieval of a document (or part of a document) given you know the key you want.
Heroku support mongo also, though hosted elsewhere (e.g. mlabs) rather than on their servers directly.
There is good support for mongo in ruby with the mongoid gem and it hides away most of the differences between that and activerecord.  I don't know if the same can be said for redis?

Having talked about document databases, it may be we can stick with postgresql - I've just been googling and came across this little gem (pun intended :-) ): https://github.com/Casecommons/pg_search which I think will give you what you want - it has multi key searching, ranking, full/partial matching etc.  Definitely worth a look IMO.

**Comment by freeranger** [comment]
@commitshappen I have been working on this and pg_search seems to do the job though there are a few issues:
* email addresses - it won't search for anything after the '@' at the moment: https://github.com/Casecommons/pg_search/issues/224
A suggested solution is to do a SQL LIKE, so we could return all the results from pg_search combined with email_address LIKE {search term}, though we wouldn't get the search results ranked according to best match unless we do something funky (not sure what?)
* numbers - this is fair enough really - how do you search for a partial match on a number?  If you want to search zip codes and phone numbers, make them strings (I thought phone numbers are usually of the form 1-800-12344 in the US? so not really a number?).  
* ranking - you can only attach your own rank to the first four matching fields - not a major limitation really as in practice, you probably aren't going to notice the lower ranked matches.

I haven't created a PR because of the email address and number issues, but I have pushed the code here so you can take a look and see what you think: https://github.com/freeranger/DSCP-Partner-Portal-API/tree/search

We could abandon pg_search completely and build our own search by hand, but it would be a bit of a pain splitting out all terms and matching them all and ranking as you'd like. 
Perhaps there is something clever we can do about email addresses?
The number thing applies whatever we do.

**Comment by freeranger** [comment]
@commitshappen perhaps you should assign it to me but mark it under review?
Would it be easier for you to review if I submitted a PR?  I didn't because it is incomplete but maybe it works better for you than grabbing my repo...

**Comment by commitshappen** [comment]
@freeranger Updated the status so people know it's being worked on. For some reason, GitHub won't let me assign you to this issue. It will only let me assign myself.

**Comment by freeranger** [comment]
@commitshappen probably because you created the issue whereas I created the others?
You would need to make me a collaborator on the project (I would have write access) or set up a team and make me a member - you can set teams to have read only access to the repo.

While I'm here, do you want to restrict the data we return from a search and add the "self" link to get all data?
Also, I see that there are only indexes on email, first_name, last_name, business_name but we are searching on a lot more fields - that could make it slow with large data sets...

**Comment by commitshappen** [comment]
@freeranger I started an organization and may move the repos there. That way I can create team and better manage individual members. 

> While I'm here, do you want to restrict the data we return from a search and add the "self" link to get all data?

I would return the same information describe in issue #20 

> Also, I see that there are only indexes on email, first_name, last_name, business_name but we are searching on a lot more fields - that could make it slow with large data sets...

You're absolutely right. When I was first creating the contact model, I was only thinking those items would be searched (or searched most often). It would be good to index all the attributes except website, Facebook, and Instagram links.

**Comment by freeranger** [comment]
@commitshappen indexing so many fields will slow down inserts, but if it's not high volume then maybe it doesn't matter.  Can always take them off later :)
I'm not going to work on this any more for the moment until you have time to review what I've already done in terms of searching - still need to solve the email address issue for example.

**Comment by commitshappen** [comment]
@freeranger Do you want to push your changes into a new branch? That way we can work on it and pull it in when it's finished.

**Comment by freeranger** [comment]
@commitshappen - my changes are on my "search" branch https://github.com/freeranger/DSCP-Partner-Portal-API/tree/search - I can't create a branch in your repo because I don't have right to do so.
You could create a search branch and I can submit a PR to there if you like, or just look at my code.

Have a read of my previous comment about searching email addresses, zips, phone numbers etc and we can discuss where to go from here.
